### ISSUE TITLE
Double-tapping the logo in the top-left corner has issues.

### ISSUE THREAD

**Issue by PiggyPlex** [sytespace/Native#10]
By the looks of it it is meant to minimise and maximise the tab, which does work when you adjust the size of the tab or when you first opened the tab. However, when you tap the fullscreen butotn then try double-tapping the logo it does not work.

**Comment by MM-coder** [comment]
That isn't its intended usecase, there is a button below that that is supposed to do that but is currently bugged as specified in #1
