### ISSUE TITLE
Navigation bar has strange margins.

### ISSUE THREAD

**Issue by PiggyPlex** [sytespace/Native#11]
The home icon has margin at the top which is not seen on any other button. All the buttons except the logo in the top left have margins on the side.

**Comment by MM-coder** [comment]
Completely intended, I'm going to up the margin in a next release. Please see the `.icon-bar` class 
```
.icon-bar {
    width: 60px;
    height:100vh; /* Set a specific width */
    background-color: black; /* Dark-grey background */
    border-right: 3px solid #1e1d45; /* Will be changed to 7px in newer version*/
  }
```
