### ISSUE TITLE
SyteSpace logo in the top left's move and size feature does not work.

### ISSUE THREAD

**Issue by PiggyPlex** [sytespace/Native#12]
Right clicking the SyteSpace logo in the top left and clicking Move or Size, then trying to move the tab does nothing.

**Comment by MM-coder** [comment]
If you click the logo and drag you can drag the application around. Will be adding the css property ```cursor: move``` to the logo

**Comment by PiggyPlex** [comment]
I don't think you get what I mean. I mean right clicking the logo THEN clicking Move. I am aware that you can already move it.

**Comment by MM-coder** [comment]
Okey, I misunderstood, it appears that'll be an OS/electron problem then

**Comment by PiggyPlex** [comment]
Simple fix: get rid of `frame: none`. This fixes almost half of the problems here.

**Comment by MM-coder** [comment]
>Simple fix: get rid of frame: none. This fixes almost half of the problems here.

I prefer it without a frame but I'll leave it up to the community so I'll mark this as "Help Wanted" and let others decide

**Comment by PiggyPlex** [comment]
If you want it with a frame, react with 👍 else feel free to leave a 👎.

**Comment by MM-coder** [comment]
Fixed in commit `28a475e `

**Comment by MM-coder** [comment]
Fixed in latest version by adding the frame back in
