### ISSUE TITLE
You cannot deselect content after doing CTL+A.

### ISSUE THREAD

**Issue by PiggyPlex** [sytespace/Native#13]
On Windows, when doing CTL+A to select everything on the page, you cannot deselect anything from the page.

**Comment by Wallvon** [comment]
I can deselect when I do CTRL+A
https://gyazo.com/9c4c5f1e841aa5767bd225df16c4a2e2

**Comment by PiggyPlex** [comment]
That's odd cause I can't.

**Comment by MM-coder** [comment]
What Windows version are you on @PiggyPlex  @Wallvon

**Comment by Wallvon** [comment]
Windows 10 Build 1809

**Comment by PiggyPlex** [comment]
Exactly the same here.

**Comment by PiggyPlex** [comment]
https://gyazo.com/2bac1964d40134c16005e4a0c4061461

**Comment by Wallvon** [comment]
That's really odd because I can do that.

**Comment by PiggyPlex** [comment]
Oh, you mean by doing CTL+A again?
I mean by clicking out which works on the main website.

**Comment by PiggyPlex** [comment]
Even then, repeating CTL+A again still doesn't work ;-;

**Comment by Wallvon** [comment]
No, I don't I also mean by clicking out.
https://gyazo.com/d5e0310eeb5a42839a756766d729a84c

**Comment by MM-coder** [comment]
I'm going to close this in light that I can't replicate the issue, it seems to be a problem on @PiggyPlex's machine
