### ISSUE TITLE
App not signed

### ISSUE THREAD

**Issue by PiggyPlex** [sytespace/Native#2]
Windows Defender & other antiviruses detect this program as from an unverified program; you have to force Chrome to keep the file, and when you open it you have to click for more information and click open anyways.

**Comment by Wallvon** [comment]
He will probably do this in one of the next updates. (this isn't a bug)

**Comment by MM-coder** [comment]
> He will probably do this in one of the next updates.

Indeed but their must be a staff meeting regarding this issue since code signing certificates are pretty expensive.

**Comment by Wallvon** [comment]
> > He will probably do this in one of the next updates.
> 
> Indeed but their must be a staff meeting regarding this issue since code signing certificates are pretty expensive.

well rip

**Comment by PiggyPlex** [comment]
For now you could just ZIP it up and include a `.bat` file temporarily opening it up 😂
Neither practical nor looks good but it could work for now owo

**Comment by Wallvon** [comment]
@MM-coder https://docs.microsoft.com/en-us/windows/win32/appxpkg/how-to-sign-a-package-using-signtool (It says you can do it using the Windows SDK)

**Comment by PiggyPlex** [comment]
oh lol nice

**Comment by MM-coder** [comment]
> @MM-coder https://docs.microsoft.com/en-us/windows/win32/appxpkg/how-to-sign-a-package-using-signtool (It says you can do it using the Windows SDK)

Yes, but you need a certificate or it won't sign

**Comment by MM-coder** [comment]
@all-contributors please add @PiggyPlex  for Helping find lots of bugs

**Comment by MM-coder** [comment]
@all-contributors please add @Wallvon for Tests

**Comment by MM-coder** [comment]
Closing,  code-signing certificate not a priority
