### ISSUE TITLE
Buttons for minimising, maximising, and closing at the top?

### ISSUE THREAD

**Issue by PiggyPlex** [sytespace/Native#4]
Not compulsory, but I'd like to see a window title at the top along with a minimising, maximising, and closing at the top.

**Comment by Wallvon** [comment]
It's personal preference, but if I look at how the app is built with the menubar at the left-hand side it will be best to put a minimize button on the left side above the close button.

**Comment by PiggyPlex** [comment]
I respect that and all, but then external links and other features can be a bit buggy. I do kind of like the uniqueness of having a sidebar menu, however:
a) The panel already features one
b) Adding a menu at the top fixes LOADS of the issues which I have reported

**Comment by MM-coder** [comment]
@Wallvon, the ordering will be changed, I do prefer the minimize one first and then close at the bottom

**Comment by MM-coder** [comment]
> I respect that and all, but then external links and other features can be a bit buggy. I do kind of like the uniqueness of having a sidebar menu, however:
a) The panel already features one
b) Adding a menu at the top fixes LOADS of the issues which I have reported

I'll be making an internal poll for staff to decide if I shall add the topbar

**Comment by PiggyPlex** [comment]
All right, sounds good.

**Comment by MM-coder** [comment]
Fixed in latest version
