### ISSUE TITLE
When the height of the window is too small, the icons squish together.

### ISSUE THREAD

**Issue by PiggyPlex** [sytespace/Native#5]
When you resize the height of the window to a very small amount, the icons can overlap.

**Comment by MM-coder** [comment]
Could you provide a screenshot of this issue I'm unable to recreate it myself

**Comment by MM-coder** [comment]
I have managed to replicate this, this is caused by the last icon, close icon having the property `bottom: 0` this isn't something pressing nor problematic since the resolutions at witch this problem originates are unthinkable for any modern devices
