### ISSUE TITLE
The app by default displays the mobile version.

### ISSUE THREAD

**Issue by PiggyPlex** [sytespace/Native#6]
The app does not start in full window, therefore displaying the mobile version by default.

**Comment by Wallvon** [comment]
Some people like that it doesn't start in full window mode. Some other applications also do this kind of stuff.

**Comment by PiggyPlex** [comment]
Yeah, but at least start it in the desktop version ;-;

**Comment by MM-coder** [comment]
What dimensions would seem appealing to you @PiggyPlex ?

**Comment by MM-coder** [comment]
Deciding to close this. No consensus was found
