### ISSUE TITLE
Clicking external links opens in a new, unclosable tab.

### ISSUE THREAD

**Issue by PiggyPlex** [sytespace/Native#7]
When you click external links (e.g. for "WHMCompleteSolution" in "Powered by WHMCompleteSolution" opens a popup for the website" or for the Twitter), it opens a new tab without a window name, control buttons (minimise, maximise, and close) which makes it very hard to close the popups.

**Comment by MM-coder** [comment]
Its a problem with electron since when the main window is created It's created with the `frame: none` option

**Comment by Wallvon** [comment]
You can actually close it by doing this:
https://gyazo.com/6b6dd15a61672f360b17b840e98867dc

**Comment by PiggyPlex** [comment]
I am aware that you created it using `frame: none`. But what exactly is the point of that? I wouldn't mind having a top bar. I am also aware that there are MANY other ways of closing it; but shouldn't there be an easier way?

**Comment by MM-coder** [comment]
That I'm aware of their isn't one, aldo if you find one feel free to respond

**Comment by MM-coder** [comment]
Fixed in commit `28a475e `

**Comment by MM-coder** [comment]
Fixed in latest release because frame=false was removed @PiggyPlex
