### ISSUE TITLE
Opening up installer closes the app.

### ISSUE THREAD

**Issue by PiggyPlex** [sytespace/Native#9]
If you open the app then open the installer, the installer closes the application.

**Comment by Wallvon** [comment]
That is because the installer overwrites the files of the application that is open so this isn't a bug of any kind.

**Comment by PiggyPlex** [comment]
👌 Fair enough

**Comment by MM-coder** [comment]
> That is because the installer overwrites the files of the application that is open so this isn't a bug of any kind.

Indeed, this is what is occuring, to even prevent this I'll be adding clearer prompts to when the installation has completed
